//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int IdCuenta { get; set; }
        public int IdPaciente { get; set; }
        public int NumHistMedico { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
