//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalCoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdPago { get; set; }
        public int NumHistMedico { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string IsWeb { get; set; }
    }
}
